name: pytest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade poetry
        POETRY_VIRTUALENVS_CREATE=false
        poetry install --all-extras
    - name: Test with pytest
      run: pytest
