name: python-tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  python-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v3
    - name: poetry install
      run: |
        python -m pip install --upgrade poetry
        export POETRY_VIRTUALENVS_CREATE=false
        poetry install --all-extras
    - run: mypy .
    - run: pytest
    - run: black --check .
